//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThomasTech.Apps.FamilyTreeWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberDate
    {
        public int ID { get; set; }
        public string DateTitle { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> MemberID { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
